### ISSUE TITLE
VLAN Tagging

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ethernet#15]
My reaction to the text added in regards to VLAN tagging: 
"While the protocol as described can proxy Ethernet frames with 802.1Q VLAN tags, it is RECOMMENDED that individual VLANs be proxied in separate connections, and VLAN tags be stripped and applied by the Ethernet proxying endpoints as needed."

Does VLAN tagging need to be signalled on HTTP level? If one is to strip and re-insert or map them rathern than transfer them over the Ethernet tunnel then one might need labels on the request for what VLAN tag to apply if any. In one mental model each connect requrest for ethernet creates an additional ethernet port, which local switching/bridging behavior then needs to be applied to, like tagging. Will thus this virtual ports needs labels to handle this, or even explicit tagging instruction on the other side? How are one otherwise expected to keep them seperated from each other?

**Comment by asedeno** [comment]
If the VLAN tags are being transmitted in the proxied Ethernet frames, then it should be handled by Ethernet switch or bridge or whatever is handling the bits that are out of scope for the protocol.

If you're using separate connections for different VLANs and stripping/reapplying the VLAN tags, I imagine the VLAN getting signaled in the URL that is used to establish the connection, though not in the form of, "please tag these packets with VLAN tag NN," but more like, "please establish a connection to the WiFi[^1] Ethernet segment." In this case, the Ethernet proxy would be configured to tag those Frames, or would drop those packets untagged onto a port on that VLAN.

The details of how Ethernet frames get to the desired Ethernet segment is outside the scope of the protocol for moving Ethernet frames over HTTP. The details for this should be agreed upon by the Ethernet proxying endpoints in advance.

[^1]: WiFi chosen as an arbitrary example of a thing I've seen separate VLANs for.

**Comment by asedeno** [comment]
I think this was well covered in the changes made when closing #19. Feel free to re-open if more discussion is needed
