### ISSUE TITLE
Why limit to Ethernet? connect-pseudowire?

### ISSUE THREAD

**Issue by asedeno** [ietf-wg-masque/draft-ietf-masque-connect-ethernet#4]
Should this draft be made more generic, and draw more inspiration from the PWE3 WG [^1]?

At IETF-118, it was suggested we limit scope, build our minimum viable product, and define our extension points.

The `connect-ethernet` method is definitely limiting scope, and invites a plethora of `connect-${my_favorite_L2_protocol_here}` followup documents.

A `connect-pseudowire` method and associated frame-type negotiation, with an included Ethernet example, could be later extended to support other Layer 2 Protocols. If we go down this path, we should consider the work of the PWE3 WG.

Independent of this, I'll be opening some other issues that reference the work of the PWE3 WG.

[^1]: https://datatracker.ietf.org/wg/pwe3/about/

**Comment by DavidSchinazi** [comment]
My preference would be to keep this scoped to connect-ethernet. Creating connect-something-else when that's needed is a better choice since that'll ensure proper analysis of that specific L2 is performed.

**Comment by asedeno** [comment]
Having thought about this some more, I've remembered that we're not implementing a new HTTP method, per se, but using extended connect for H2/H3 and upgrade for H1. We don't need to invent an L2-specific extended-extended-connect. New values for the `Upgrade` / `:protocol` headers are already cheap.
