### ISSUE TITLE
Why are we transmitting the Frame Check Sequence?

### ISSUE THREAD

**Issue by asedeno** [ietf-wg-masque/draft-ietf-masque-connect-ethernet#5]
Section 6 of the draft states that Context ID 0 indicates that the Datagram carries

> a full Layer 2 Ethernet Frame (from the MAC destination field until the last byte of the Frame check sequence field).

The Frame check sequence is a four octet CRC that we could recalculate on the receiving Ethernet proxying endpoint. If we drop and recompute it, we eke out 4 additional octets of payload.

**Comment by achernya** [comment]
In CONNECT-IP we left header compression to future context IDs. I think you could do the same here? You're trading off space vs compute power.

**Comment by asedeno** [comment]
Sure, let's return to this in future header compression work if that happens.
