### ISSUE TITLE
Special consideration for Ethernet PAUSE frames

### ISSUE THREAD

**Issue by asedeno** [ietf-wg-masque/draft-ietf-masque-connect-ethernet#7]
More from PWE3: 

https://www.rfc-editor.org/rfc/rfc4448.html#section-4.4.5
> In a standard Ethernet network, the flow control mechanism is optional and typically configured between the two nodes on a point-to-point link (e.g., between the CE and the PE).  IEEE 802.3x PAUSE frames MUST NOT be carried across the PW.  See [Appendix A](https://www.rfc-editor.org/rfc/rfc4448.html#appendix-A) for notes on CE-PE flow control.

https://www.rfc-editor.org/rfc/rfc4448.html#appendix-A.2 has the specific notes on PAUSE frame.

This does not seem common anymore. We probably still don't want to proxy it. Otherwise emitting or reacting to PAUSE frames do not appear to be in scope for this draft.

**Comment by achernya** [comment]
I think we should not respect PAUSE frames. That can be left to a future extension if we can define a semantic that makes sense. (PAUSE frames can result in DoS if used incorrectly)
